#!/usr/bin/env python3
"""Minimal multitel3 vs CPS GF comparison (fixed sp6/raysp6prem)."""

from __future__ import annotations

import argparse
import math
import os
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

import numpy as np
from obspy.io.sac.sactrace import SACTrace

# Keep matplotlib cache writable in restricted environments.
if "MPLCONFIGDIR" not in os.environ:
    os.environ["MPLCONFIGDIR"] = "/tmp/mplconfig"

import matplotlib.pyplot as plt

COMPONENTS: Tuple[str, ...] = (
    "ZDD",
    "RDD",
    "TDD",
    "ZDS",
    "RDS",
    "TDS",
    "ZSS",
    "RSS",
    "TSS",
)

MTEL_INDEX_TO_COMPONENT: Dict[int, str] = {
    0: "ZDD",
    1: "RDD",
    2: "TDD",
    3: "ZDS",
    4: "RDS",
    5: "TDS",
    6: "ZSS",
    7: "RSS",
    8: "TSS",
}

SAC_NULL = -12345.0
KM_PER_DEG = 111.195

MODEL96_HEADER_LINES: Tuple[str, ...] = (
    "MODEL.01",
    "Generated by gf_compare",
    "ISOTROPIC",
    "KGS",
    "SPHERICAL EARTH",
    "1-D",
    "CONSTANT VELOCITY",
    "LINE08",
    "LINE09",
    "LINE10",
    "LINE11",
    "      H(KM)   VP(KM/S)   VS(KM/S) RHO(GM/CC)         QP         QS       ETAP       ETAS      FREFP      FREFS",
)

DEFAULT_NPTS = 8192
DEFAULT_DT = 0.05
DEFAULT_WINDOW_PRE = 10.0
DEFAULT_WINDOW_POST = 200.0
DEFAULT_DEPTH_TOL = 0.5
DEFAULT_GCARC_TOL = 0.2
DEFAULT_CMB_DEPTH_KM = 2891.0


@dataclass
class GFRecord:
    model: str
    depth: float
    gcarc: float
    component: str
    dt: float
    npts: int
    b: float
    t1: Optional[float]
    t2: Optional[float]
    t3: Optional[float]
    series: np.ndarray
    source: str
    path: str
    picks: Dict[str, float]


def _die(msg: str) -> None:
    raise RuntimeError(msg)


def _maybe_int_string(v: float) -> str:
    if abs(v - round(v)) < 1.0e-9:
        return str(int(round(v)))
    return f"{v:g}"


def _is_null(v: Optional[float]) -> bool:
    if v is None:
        return True
    if isinstance(v, float) and (math.isnan(v) or math.isinf(v)):
        return True
    return abs(float(v) - SAC_NULL) < 1.0e-3


def _safe_float(v: object) -> Optional[float]:
    try:
        return float(v)
    except Exception:
        return None


def _sac_pick(sac_obj: object, key: str) -> Optional[float]:
    if sac_obj is None:
        return None
    if not hasattr(sac_obj, key):
        return None
    v = _safe_float(getattr(sac_obj, key))
    if _is_null(v):
        return None
    return float(v)


def _extract_component(path: Path) -> Optional[str]:
    name = path.name.upper()
    for comp in COMPONENTS:
        if name.endswith(f".{comp}") or name.endswith(f".{comp}.SAC"):
            return comp
    if ".GRN." in name:
        suffix = name.split(".GRN.")[-1]
        if suffix.endswith(".SAC"):
            suffix = suffix[:-4]
        try:
            idx = int(suffix)
        except Exception:
            return None
        return MTEL_INDEX_TO_COMPONENT.get(idx)
    return None


def _extract_multitel_depth_hint(path: Path) -> Optional[float]:
    for part in reversed(path.parts):
        low = part.lower()
        if "direct_" in low or "core_" in low:
            try:
                return float(low.split("_")[-1])
            except Exception:
                continue
    return None


def _extract_multitel_gcarc_hint(path: Path) -> Optional[float]:
    name = path.name
    if ".grn." not in name:
        return None
    try:
        return float(name.split(".grn.")[0])
    except Exception:
        return None


def _read_one_sac(
    path: Path,
    source: str,
    model: str,
    component_hint: Optional[str] = None,
    depth_hint: Optional[float] = None,
    gcarc_hint: Optional[float] = None,
) -> Optional[GFRecord]:
    try:
        sac = SACTrace.read(str(path), headonly=False)
    except Exception:
        return None
    comp = component_hint or _extract_component(path)
    if comp is None:
        return None

    b = _sac_pick(sac, "b")
    if b is None:
        b = 0.0

    gcarc = _sac_pick(sac, "gcarc")
    if gcarc is None:
        dist = _sac_pick(sac, "dist")
        if dist is not None:
            gcarc = dist / KM_PER_DEG
    if gcarc is None and gcarc_hint is not None:
        gcarc = float(gcarc_hint)
    if gcarc is None:
        gcarc = math.nan

    depth = _sac_pick(sac, "evdp")
    if depth is None:
        depth = _sac_pick(sac, "evdep")
    if depth is None and depth_hint is not None:
        depth = float(depth_hint)
    if depth is None:
        depth = math.nan

    picks: Dict[str, float] = {}
    for key in ("a", "t0", "t1", "t2", "t3"):
        val = _sac_pick(sac, key)
        if val is not None:
            picks[key] = val

    data = np.asarray(sac.data, dtype=np.float64)
    return GFRecord(
        model=model,
        depth=depth,
        gcarc=gcarc,
        component=comp,
        dt=float(sac.delta),
        npts=int(sac.npts),
        b=float(b),
        t1=picks.get("t1"),
        t2=picks.get("t2"),
        t3=picks.get("t3"),
        series=data,
        source=source,
        path=str(path),
        picks=picks,
    )


def load_records(root: Path, source: str, model: str) -> List[GFRecord]:
    out: List[GFRecord] = []
    for p in sorted(root.rglob("*")):
        if not p.is_file():
            continue
        comp = _extract_component(p)
        if comp is None:
            continue
        depth_hint = _extract_multitel_depth_hint(p) if source.startswith("multitel") else None
        gcarc_hint = _extract_multitel_gcarc_hint(p) if source.startswith("multitel") else None
        rec = _read_one_sac(
            p,
            source=source,
            model=model,
            component_hint=comp,
            depth_hint=depth_hint,
            gcarc_hint=gcarc_hint,
        )
        if rec is not None:
            out.append(rec)
    return out


def _parse_numeric_line(line: str) -> List[float]:
    vals: List[float] = []
    for tok in line.replace(",", " ").split():
        try:
            vals.append(float(tok))
        except Exception:
            return []
    return vals


def parse_multitel_crust(path: Path) -> Dict[str, List[Dict[str, float]]]:
    raw: List[float] = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            raw.extend(_parse_numeric_line(line))
    if not raw:
        _die(f"cannot parse multitel crust model: {path}")

    idx = 0
    nsrc = int(raw[idx])
    idx += 1
    src: List[Dict[str, float]] = []
    for _ in range(nsrc):
        vp, vs, rho, h = raw[idx : idx + 4]
        idx += 4
        src.append({"vp": vp, "vs": vs, "rho": rho, "h": h})

    nrec = int(raw[idx])
    idx += 1
    rec: List[Dict[str, float]] = []
    for _ in range(nrec):
        vp, vs, rho, h = raw[idx : idx + 4]
        idx += 4
        rec.append({"vp": vp, "vs": vs, "rho": rho, "h": h})

    return {"source": src, "receiver": rec}


def parse_multitel_ray(path: Path) -> List[Dict[str, float]]:
    rows: List[Dict[str, float]] = []
    with path.open("r", encoding="utf-8") as f:
        first = f.readline().strip().split()
        if not first:
            _die(f"empty multitel ray model: {path}")
        n = int(float(first[0]))
        for _ in range(n):
            line = f.readline()
            if not line:
                break
            vals = _parse_numeric_line(line)
            if len(vals) < 4:
                continue
            depth, vp, vs, rho = vals[:4]
            qp = vals[4] if len(vals) >= 5 else float("nan")
            qs = vals[5] if len(vals) >= 6 else float("nan")
            rows.append({"depth": depth, "vp": vp, "vs": vs, "rho": rho, "qp": qp, "qs": qs})
    if not rows:
        _die(f"cannot parse multitel ray model: {path}")
    return rows


def _ensure_ray_has_q(ray_rows: Sequence[Dict[str, float]], source_path: Path) -> None:
    for i, row in enumerate(ray_rows):
        qp = float(row.get("qp", float("nan")))
        qs = float(row.get("qs", float("nan")))
        if math.isnan(qp) or math.isnan(qs):
            _die(f"ray model missing QP/QS at row {i + 1} in {source_path}")


def _clean_sorted_ray_rows(ray_rows: Sequence[Dict[str, float]]) -> List[Dict[str, float]]:
    out = [dict(row) for row in ray_rows]
    out.sort(key=lambda r: float(r["depth"]))
    return out


def _ray_to_cps_tel_layers(ray_rows: Sequence[Dict[str, float]]) -> List[Dict[str, float]]:
    rows = _clean_sorted_ray_rows(ray_rows)
    layers: List[Dict[str, float]] = []
    eps = 1.0e-9
    for i in range(len(rows) - 1):
        top = rows[i]
        bot = rows[i + 1]
        h = float(bot["depth"]) - float(top["depth"])
        if h <= eps:
            continue
        layers.append(
            {
                "h": h,
                "vp": float(top["vp"]),
                "vs": float(top["vs"]),
                "rho": float(top["rho"]),
                "qp": float(top["qp"]),
                "qs": float(top["qs"]),
            }
        )
    if not layers:
        _die("cannot build cps tel model")
    last = rows[-1]
    layers.append(
        {
            "h": 0.0,
            "vp": float(last["vp"]),
            "vs": float(last["vs"]),
            "rho": float(last["rho"]),
            "qp": float(last["qp"]),
            "qs": float(last["qs"]),
        }
    )
    return layers


def value_in_depth_table(rows: Sequence[Dict[str, float]], depth: float, key: str) -> float:
    val = float(rows[0][key])
    for row in rows:
        if depth + 1.0e-9 < row["depth"]:
            break
        val = float(row[key])
    return val


def _sp6_source_to_cps_src_layers(
    source_layers: Sequence[Dict[str, float]],
    ray_rows: Sequence[Dict[str, float]],
) -> List[Dict[str, float]]:
    out: List[Dict[str, float]] = []
    cur_depth = 0.0
    has_halfspace = False
    for row in source_layers:
        h = float(row["h"])
        sample_depth = cur_depth + 0.5 * h if h > 0.0 else cur_depth
        qp = float(value_in_depth_table(ray_rows, sample_depth, "qp"))
        qs = float(value_in_depth_table(ray_rows, sample_depth, "qs"))
        out.append(
            {
                "h": h if h > 0.0 else 0.0,
                "vp": float(row["vp"]),
                "vs": float(row["vs"]),
                "rho": float(row["rho"]),
                "qp": qp,
                "qs": qs,
            }
        )
        if h > 0.0:
            cur_depth += h
        else:
            has_halfspace = True
            break
    if not out:
        _die("cannot build cps src model")
    if not has_halfspace:
        last = dict(out[-1])
        last["h"] = 0.0
        out.append(last)
    return out


def _write_cps_model96(path: Path, layers: Sequence[Dict[str, float]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        for line in MODEL96_HEADER_LINES:
            f.write(line + "\n")
        for row in layers:
            h = float(row["h"])
            vp = float(row["vp"])
            vs = float(row["vs"])
            rho = float(row["rho"])
            qp = float(row["qp"])
            qs = float(row["qs"])
            etap = float(row.get("etap", 0.0))
            etas = float(row.get("etas", 0.0))
            frefp = float(row.get("frefp", 1.0))
            frefs = float(row.get("frefs", 1.0))
            f.write(
                f"{h:10.4f} {vp:10.4f} {vs:10.4f} {rho:10.4f} "
                f"{qp:10.3f} {qs:10.3f} {etap:10.2f} {etas:10.2f} {frefp:10.2f} {frefs:10.2f}\n"
            )


def _collect_generated_dir(parent: Path, prefix: str) -> Path:
    cands = [p for p in parent.iterdir() if p.is_dir() and p.name.startswith(prefix)]
    if not cands:
        _die(f"cannot find generated directory: {prefix}")
    cands.sort(key=lambda p: p.stat().st_mtime)
    return cands[-1]


def _build_grid(start: float, end: float, dt: float) -> np.ndarray:
    n = int(round((end - start) / dt)) + 1
    return start + np.arange(max(n, 1), dtype=np.float64) * dt


def _interp_record(rec: GFRecord, grid: np.ndarray) -> np.ndarray:
    t = rec.b + np.arange(rec.npts, dtype=np.float64) * rec.dt
    return np.interp(grid, t, rec.series, left=0.0, right=0.0)


def _run(cmd: Sequence[str], cwd: Optional[Path] = None) -> None:
    res = subprocess.run(cmd, cwd=str(cwd) if cwd else None, capture_output=True, text=True)
    if res.returncode != 0:
        err_lines = [ln for ln in res.stderr.strip().splitlines() if ln.strip()]
        tail_lines = err_lines[-12:] if err_lines else []
        tail = "\n".join(tail_lines)
        summary = f"command failed (exit={res.returncode}): {' '.join(cmd[:3])} ..."
        if tail:
            raise RuntimeError(f"{summary}\n{tail}")
        raise RuntimeError(summary)


def _clean_dir(path: Path) -> None:
    if path.exists():
        shutil.rmtree(path)
    path.mkdir(parents=True, exist_ok=True)


def _copy_input(src: Path, dst: Path) -> Path:
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)
    return dst


def _copy_hudson_models_to_output(
    output_root: Path,
    tel_model: Path,
    src_model: Path,
    rec_model: Path,
) -> Path:
    dst_dir = output_root / "models" / "hudson96"
    _clean_dir(dst_dir)
    _copy_input(tel_model, dst_dir / "cps_tel.mod")
    _copy_input(src_model, dst_dir / "cps_src.mod")
    _copy_input(rec_model, dst_dir / "cps_rec.mod")
    return dst_dir


def _in_tol(value: float, target: float, tol: float) -> bool:
    if math.isnan(value):
        return False
    return abs(value - target) <= tol


def _score_record(rec: GFRecord, depth: float, gcarc: float) -> float:
    ds = abs(rec.depth - depth) if not math.isnan(rec.depth) else 10.0
    gs = abs(rec.gcarc - gcarc) if not math.isnan(rec.gcarc) else 10.0
    return ds + gs


def _select_by_depth_gcarc(
    records: Sequence[GFRecord],
    depth_km: float,
    gcarc_deg: float,
    depth_tol: float,
    gcarc_tol: float,
) -> Dict[str, GFRecord]:
    out: Dict[str, GFRecord] = {}
    for comp in COMPONENTS:
        cands = [
            r
            for r in records
            if r.component == comp and _in_tol(r.depth, depth_km, depth_tol) and _in_tol(r.gcarc, gcarc_deg, gcarc_tol)
        ]
        if not cands:
            continue
        cands.sort(key=lambda r: _score_record(r, depth_km, gcarc_deg))
        out[comp] = cands[0]
    return out


def _build_tel_layers_to_cmb_with_core_halfspace(
    ray_rows: Sequence[Dict[str, float]],
    cmb_depth_km: float = DEFAULT_CMB_DEPTH_KM,
) -> List[Dict[str, float]]:
    """Build TEL layers to CMB, plus one core halfspace layer."""
    rows = _clean_sorted_ray_rows(ray_rows)
    if not rows:
        _die("empty ray model rows.")

    eps = 1.0e-6
    mantle_idx: Optional[int] = None
    core_idx: Optional[int] = None

    for i, row in enumerate(rows):
        depth = float(row["depth"])
        vs = float(row["vs"])
        if depth <= cmb_depth_km + eps and vs > eps:
            mantle_idx = i
        if core_idx is None and depth >= cmb_depth_km - eps and abs(vs) <= eps:
            core_idx = i

    if mantle_idx is None:
        _die(f"cannot identify mantle-side row near CMB={cmb_depth_km:g} km in ray model.")

    mantle_rows = [dict(r) for r in rows[: mantle_idx + 1]]
    if len(mantle_rows) < 2:
        _die("insufficient mantle rows to build TEL finite layers.")

    tel_layers = _ray_to_cps_tel_layers(mantle_rows)

    if core_idx is None:
        _die(f"cannot identify core-side row near CMB={cmb_depth_km:g} km in ray model.")
    core_row = rows[core_idx]

    tel_layers[-1] = {
        "h": 0.0,
        "vp": float(core_row["vp"]),
        "vs": float(core_row["vs"]),
        "rho": float(core_row["rho"]),
        "qp": float(core_row["qp"]),
        "qs": float(core_row["qs"]),
    }
    return tel_layers


def _combine_direct_core(direct: GFRecord, core: GFRecord) -> GFRecord:
    dt = min(direct.dt, core.dt)
    direct_end = direct.b + (direct.npts - 1) * direct.dt
    core_end = core.b + (core.npts - 1) * core.dt
    start = min(direct.b, core.b)
    end = max(direct_end, core_end)
    grid = _build_grid(start, end, dt)

    d = _interp_record(direct, grid)
    c = _interp_record(core, grid)
    merged = d + c

    return GFRecord(
        model=direct.model,
        depth=direct.depth,
        gcarc=direct.gcarc,
        component=direct.component,
        dt=dt,
        npts=len(grid),
        b=float(start),
        t1=direct.t1,
        t2=direct.t2,
        t3=direct.t3,
        series=merged,
        source="multitel_direct_plus_core",
        path=f"{direct.path} + {core.path}",
        picks=dict(direct.picks),
    )


def _pick_phase_anchor(rec: GFRecord, phase: str) -> float:
    if phase == "SH":
        order = ("t2", "t1", "t0", "a", "t3")
    else:
        order = ("t1", "a", "t0", "t3", "t2")
    for key in order:
        if key in rec.picks:
            return float(rec.picks[key])
    idx = int(np.argmax(np.abs(rec.series)))
    return float(rec.b + idx * rec.dt)


def _interp_relative(rec: GFRecord, anchor: float, t_axis: np.ndarray) -> np.ndarray:
    t_abs = anchor + t_axis
    t = rec.b + np.arange(rec.npts, dtype=np.float64) * rec.dt
    return np.interp(t_abs, t, rec.series, left=0.0, right=0.0)


def _maxabs_or_one(x: np.ndarray) -> float:
    if x.size == 0:
        return 1.0
    val = float(np.max(np.abs(x)))
    return val if val > 0.0 else 1.0


def _record_to_sac(rec: GFRecord) -> SACTrace:
    hdr: Dict[str, float] = {
        "b": float(rec.b),
        "delta": float(rec.dt),
    }
    if not math.isnan(rec.depth):
        hdr["evdp"] = float(rec.depth)
    if not math.isnan(rec.gcarc):
        hdr["gcarc"] = float(rec.gcarc)
        hdr["dist"] = float(rec.gcarc * KM_PER_DEG)
    for key in ("a", "t0", "t1", "t2", "t3"):
        if key in rec.picks and np.isfinite(float(rec.picks[key])):
            hdr[key] = float(rec.picks[key])

    return SACTrace(data=np.asarray(rec.series, dtype=np.float32), **hdr)


def _export_record_map(records: Dict[str, GFRecord], out_dir: Path) -> None:
    _clean_dir(out_dir)
    for comp in COMPONENTS:
        rec = records.get(comp)
        if rec is None:
            continue
        out = out_dir / f"{comp}.SAC"
        sac = _record_to_sac(rec)
        sac.write(str(out))


def _assert_has_9(records: Dict[str, GFRecord], label: str) -> None:
    missing = [c for c in COMPONENTS if c not in records]
    if missing:
        _die(f"{label} missing components: {','.join(missing)}")


def _plot_compare(
    direct_map: Dict[str, GFRecord],
    combo_map: Dict[str, GFRecord],
    cps_map: Dict[str, GFRecord],
    depth_km: float,
    gcarc_deg: float,
    out_png: Path,
    window_pre: float,
    window_post: float,
) -> None:
    fig, axes = plt.subplots(3, 3, figsize=(15, 12), sharex=True)
    ax_list = np.atleast_1d(axes).ravel()
    direct_drawn = 0

    for i, comp in enumerate(COMPONENTS):
        ax = ax_list[i]
        phase = "SH" if comp.startswith("T") else "P"
        drec = direct_map.get(comp)
        crec = combo_map.get(comp)
        prec = cps_map.get(comp)

        if drec is None:
            ax.text(
                0.5,
                0.5,
                f"{comp} [{phase}]\nmultitel direct missing",
                transform=ax.transAxes,
                ha="center",
                va="center",
                fontsize=9,
            )
            ax.grid(True, alpha=0.2)
            ax.set_xlim(-window_pre, window_post)
            continue

        d_anchor = _pick_phase_anchor(drec, phase)
        dt_plot = drec.dt
        if crec is not None:
            dt_plot = min(dt_plot, crec.dt)
        if prec is not None:
            dt_plot = min(dt_plot, prec.dt)

        t_axis = np.arange(-window_pre, window_post + 0.5 * dt_plot, dt_plot, dtype=np.float64)
        yd = _interp_relative(drec, d_anchor, t_axis)
        yc = None
        yp = None

        if crec is not None:
            c_anchor = _pick_phase_anchor(crec, phase)
            yc = _interp_relative(crec, c_anchor, t_axis)
        if prec is not None:
            p_anchor = _pick_phase_anchor(prec, phase)
            yp = _interp_relative(prec, p_anchor, t_axis)
            # Coordinate-system correction:
            # DS/SS in CPS are opposite to multitel convention used for plotting.
            if comp.endswith("DS") or comp.endswith("SS"):
                yp = -yp

        scale = _maxabs_or_one(yp) if yp is not None else _maxabs_or_one(yd)
        yd = yd / scale
        if yc is not None:
            yc = yc / scale
        if yp is not None:
            yp = yp / scale

        if yp is not None:
            ax.plot(t_axis, yp, color="#d62728", lw=1.2, label="CPS", zorder=1)
        ax.plot(t_axis, yd, color="#1f77b4", lw=1.2, label="multitel direct", zorder=2)
        direct_drawn += 1
        if yc is not None:
            ax.plot(t_axis, yc, color="#00a651", lw=1.2, label="multitel direct+core", zorder=3)

        tag: List[str] = []
        if yc is None:
            tag.append("combo-missing")
        if yp is None:
            tag.append("cps-missing")
        title = f"{comp} [{phase}]"
        if tag:
            title += " | " + ",".join(tag)
        ax.set_title(title, fontsize=10)
        ax.axvline(0.0, color="k", lw=0.8, alpha=0.4)
        ax.grid(True, alpha=0.2)
        ax.set_xlim(-window_pre, window_post)

    for idx, ax in enumerate(ax_list):
        row = idx // 3
        col = idx % 3
        if row == 2:
            ax.set_xlabel("Time relative to phase arrival (s)")
        if col == 0:
            ax.set_ylabel("Amplitude (normalized)")

    handles, labels = ax_list[0].get_legend_handles_labels()
    if handles:
        fig.legend(handles, labels, loc="upper right", frameon=False)

    fig.suptitle(
        f"GF Compare | depth={depth_km:.2f} km | gcarc={gcarc_deg:.2f} deg | panels=9 (include TDD)",
        fontsize=14,
    )
    fig.tight_layout(rect=(0, 0.02, 1, 0.96))
    out_png.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_png, dpi=180)
    plt.close(fig)

    if direct_drawn == 0:
        _die("no multitel direct traces were drawn; plotting failed.")


def _run_multitel(
    work_root: Path,
    depth_km: float,
    gcarc_deg: float,
    npts: int,
    dt: float,
    multitel_crust: Path,
    multitel_ray: Path,
    perl_exe: str,
    multitel_pl: str,
    multitel_bin: str,
    rayinfo_bin: str,
) -> Tuple[Path, Path]:
    mwork = work_root / "multitel"
    _clean_dir(mwork)

    mcrust = _copy_input(multitel_crust, mwork / "mtcrust")
    mray = _copy_input(multitel_ray, mwork / "mtray")

    staged_multitel = mwork / "multitel3"
    staged_rayinfo = mwork / "rayinformation"
    if staged_multitel.exists() or staged_multitel.is_symlink():
        staged_multitel.unlink()
    if staged_rayinfo.exists() or staged_rayinfo.is_symlink():
        staged_rayinfo.unlink()
    staged_multitel.symlink_to(Path(multitel_bin))
    staged_rayinfo.symlink_to(Path(rayinfo_bin))

    cmd = [
        perl_exe,
        str(Path(multitel_pl).resolve()),
        f"-M{mcrust.name}/{mray.name}/{_maybe_int_string(depth_km)}",
        "-D",
        f"-N{npts}/{dt}",
        "-O.",
        f"{gcarc_deg}",
    ]
    _run(cmd, cwd=mwork)

    direct_dir = _collect_generated_dir(mwork, f"{mcrust.name}direct_")
    core_dir = _collect_generated_dir(mwork, f"{mcrust.name}core_")
    return direct_dir, core_dir


def _build_models_fixed(
    model_dir: Path,
    tel_layers_raw: Sequence[Dict[str, float]],
    src_layers: Sequence[Dict[str, float]],
    rec_layers: Sequence[Dict[str, float]],
) -> Tuple[Path, Path, Path, int]:
    tel_layers = [dict(x) for x in tel_layers_raw]
    model_dir.mkdir(parents=True, exist_ok=True)
    tel_path = model_dir / "cps_tel.mod"
    src_path = model_dir / "cps_src.mod"
    rec_path = model_dir / "cps_rec.mod"
    _write_cps_model96(tel_path, tel_layers)
    _write_cps_model96(src_path, src_layers)
    _write_cps_model96(rec_path, rec_layers)
    return tel_path, src_path, rec_path, len(tel_layers)


def _run_cps_once(
    phase: str,
    workdir: Path,
    outdir: Path,
    depth_km: float,
    gcarc_deg: float,
    npts: int,
    dt: float,
    tel_model: Path,
    src_model: Path,
    rec_model: Path,
    hudson96: str,
    hpulse96: str,
    f96tosac: str,
) -> None:
    workdir.mkdir(parents=True, exist_ok=True)
    outdir.mkdir(parents=True, exist_ok=True)

    def _run_or_raise(cmd: Sequence[str], stdin=None, stdout=None) -> None:
        run_stdout = stdout if stdout is not None else subprocess.DEVNULL
        res = subprocess.run(
            cmd,
            cwd=str(workdir),
            stdin=stdin,
            stdout=run_stdout,
            stderr=subprocess.PIPE,
            text=True,
        )
        if res.returncode != 0:
            err_lines = [ln for ln in (res.stderr or "").splitlines() if ln.strip()]
            tail = "\n".join(err_lines[-12:])
            if tail:
                raise RuntimeError(f"CPS {phase} failed: {' '.join(cmd[:2])}\n{tail}")
            raise RuntimeError(f"CPS {phase} failed: {' '.join(cmd[:2])}")

    hudson_cmd: List[str] = [
        str(hudson96),
        "-HS",
        f"{depth_km}",
        "-GCARC",
        f"{gcarc_deg}",
        "-TEL",
        str(tel_model),
        "-NPTS",
        str(npts),
        "-DT",
        str(dt),
        "-SRC",
        str(src_model),
        "-REC",
        str(rec_model),
    ]
    if str(phase).upper() == "S":
        hudson_cmd.append("-S")
    _run_or_raise(hudson_cmd)

    file96_path = workdir / "file96"
    with file96_path.open("w", encoding="utf-8") as f96w:
        _run_or_raise([str(hpulse96), "-i", "-V"], stdout=f96w)
    with file96_path.open("r", encoding="utf-8") as f96r:
        _run_or_raise([str(f96tosac), "-T"], stdin=f96r)

    exported: List[Path] = []
    for p in sorted(workdir.glob("*")):
        if not p.is_file():
            continue
        if _extract_component(p) is None:
            continue
        outp = outdir / p.name
        shutil.copy2(p, outp)
        exported.append(outp)

    # P-run may miss transverse components; fill zero traces to keep strict 9 components.
    groups: Dict[str, Dict[str, Path]] = {}
    for p in exported:
        comp = _extract_component(p)
        if comp is None:
            continue
        name = p.name[:-4] if p.name.upper().endswith(".SAC") else p.name
        suffix = f".{comp}"
        base = name[: -len(suffix)] if name.upper().endswith(suffix) else name.rsplit(".", 1)[0]
        groups.setdefault(base, {})[comp] = p

    for _base, comp_map in groups.items():
        if not comp_map:
            continue
        ref_path = next(iter(comp_map.values()))
        ref_sac = SACTrace.read(str(ref_path), headonly=False)
        for comp in COMPONENTS:
            if comp in comp_map:
                continue
            outp = outdir / f"{_base}.{comp}"
            if outp.exists():
                continue
            syn = ref_sac.copy()
            syn.data = np.zeros(ref_sac.npts, dtype=np.float32)
            syn.write(str(outp))


def _trace_has_finite_samples(rec: Optional[GFRecord]) -> bool:
    if rec is None:
        return False
    arr = np.asarray(rec.series, dtype=np.float64)
    if arr.size == 0:
        return False
    return bool(np.isfinite(arr).any())


def _trace_has_nan(rec: Optional[GFRecord]) -> bool:
    if rec is None:
        return True
    arr = np.asarray(rec.series, dtype=np.float64)
    if arr.size == 0:
        return True
    return bool(np.isnan(arr).any())


def _trace_maxabs(rec: Optional[GFRecord]) -> float:
    if rec is None:
        return 0.0
    arr = np.asarray(rec.series, dtype=np.float64)
    if arr.size == 0:
        return 0.0
    finite = arr[np.isfinite(arr)]
    if finite.size == 0:
        return 0.0
    return float(np.max(np.abs(finite)))


def _cps_outputs_valid(
    p_out: Path,
    s_out: Path,
    depth_km: float,
    gcarc_deg: float,
) -> bool:
    p_records = load_records(p_out, source="cps_p", model="sp6")
    s_records = load_records(s_out, source="cps_s", model="sp6")
    p_map = _select_by_depth_gcarc(
        p_records,
        depth_km=depth_km,
        gcarc_deg=gcarc_deg,
        depth_tol=float(DEFAULT_DEPTH_TOL),
        gcarc_tol=float(DEFAULT_GCARC_TOL),
    )
    s_map = _select_by_depth_gcarc(
        s_records,
        depth_km=depth_km,
        gcarc_deg=gcarc_deg,
        depth_tol=float(DEFAULT_DEPTH_TOL),
        gcarc_tol=float(DEFAULT_GCARC_TOL),
    )
    merged = _merge_cps_maps(p_map, s_map)

    for comp in COMPONENTS:
        rec = merged.get(comp)
        if not _trace_has_finite_samples(rec):
            return False
        if _trace_has_nan(rec):
            return False

    zr_nonzero = any(_trace_maxabs(merged.get(comp)) > 0.0 for comp in COMPONENTS if (not comp.startswith("T")))
    t_nonzero = any(_trace_maxabs(merged.get(comp)) > 0.0 for comp in COMPONENTS if comp.startswith("T"))
    if not zr_nonzero:
        return False
    if not t_nonzero:
        return False
    return True


def _run_cps_fixed_layers(
    work_root: Path,
    depth_km: float,
    gcarc_deg: float,
    npts: int,
    dt: float,
    tel_layers_raw: Sequence[Dict[str, float]],
    src_layers: Sequence[Dict[str, float]],
    rec_layers: Sequence[Dict[str, float]],
    hudson96: str,
    hpulse96: str,
    f96tosac: str,
) -> Tuple[Path, Path, Path, Path, Path, int]:
    model_dir = work_root / "models" / "tel_fixed"
    p_work = work_root / "cpsP_work"
    s_work = work_root / "cpsS_work"
    p_out = work_root / "cpsP_out"
    s_out = work_root / "cpsS_out"
    for d in (p_work, s_work, p_out, s_out):
        _clean_dir(d)

    tel_path, src_path, rec_path, tel_count = _build_models_fixed(
        model_dir=model_dir,
        tel_layers_raw=tel_layers_raw,
        src_layers=src_layers,
        rec_layers=rec_layers,
    )

    _run_cps_once(
        phase="P",
        workdir=p_work,
        outdir=p_out,
        depth_km=depth_km,
        gcarc_deg=gcarc_deg,
        npts=npts,
        dt=dt,
        tel_model=tel_path,
        src_model=src_path,
        rec_model=rec_path,
        hudson96=hudson96,
        hpulse96=hpulse96,
        f96tosac=f96tosac,
    )
    _run_cps_once(
        phase="S",
        workdir=s_work,
        outdir=s_out,
        depth_km=depth_km,
        gcarc_deg=gcarc_deg,
        npts=npts,
        dt=dt,
        tel_model=tel_path,
        src_model=src_path,
        rec_model=rec_path,
        hudson96=hudson96,
        hpulse96=hpulse96,
        f96tosac=f96tosac,
    )
    if not _cps_outputs_valid(
        p_out=p_out,
        s_out=s_out,
        depth_km=depth_km,
        gcarc_deg=gcarc_deg,
    ):
        _die("invalid CPS output with fixed TEL layers.")
    return p_out, s_out, tel_path, src_path, rec_path, tel_count


def _merge_cps_maps(
    p_map: Dict[str, GFRecord],
    s_map: Dict[str, GFRecord],
) -> Dict[str, GFRecord]:
    out: Dict[str, GFRecord] = {}
    for comp in COMPONENTS:
        if comp.startswith("T"):
            rec = s_map.get(comp)
        else:
            rec = p_map.get(comp)
        if rec is not None:
            out[comp] = rec
    return out


def _ensure_exes(repo_root: Path) -> Dict[str, str]:
    out: Dict[str, str] = {}
    perl = shutil.which("perl")
    if perl is None:
        _die("executable not found in PATH: perl")
    out["perl"] = perl

    multitel_pl = (repo_root / "multitel3.pl").resolve()
    if not multitel_pl.exists():
        _die(f"missing script file: {multitel_pl}")
    out["multitel3_pl"] = str(multitel_pl)

    for key, name in (
        ("multitel3_exe", "multitel3"),
        ("rayinformation", "rayinformation"),
        ("hudson96", "hudson96"),
        ("hpulse96", "hpulse96"),
        ("f96tosac", "f96tosac"),
    ):
        exe = shutil.which(name)
        if exe is None:
            _die(f"executable not found in PATH: {name}")
        out[key] = exe
    return out


def _run_pipeline(args: argparse.Namespace) -> None:
    repo_root = Path(__file__).resolve().parents[1]
    sp6 = repo_root / "sp6"
    raysp6prem = repo_root / "raysp6prem"
    if not sp6.exists():
        _die(f"missing model file: {sp6}")
    if not raysp6prem.exists():
        _die(f"missing model file: {raysp6prem}")

    exes = _ensure_exes(repo_root)

    output_root = Path(args.output_dir).resolve()
    output_root.mkdir(parents=True, exist_ok=True)
    greens_root = output_root / "greens"
    direct_out = greens_root / "multitel_direct"
    combo_out = greens_root / "multitel_direct_plus_core"
    cps_out = greens_root / "cps"
    fig_out_dir = output_root / "figures"
    fig_out_dir.mkdir(parents=True, exist_ok=True)
    work_root = output_root / ".work"
    _clean_dir(work_root)

    try:
        m_direct_dir, m_core_dir = _run_multitel(
            work_root=work_root,
            depth_km=float(args.depth_km),
            gcarc_deg=float(args.gcarc_deg),
            npts=int(DEFAULT_NPTS),
            dt=float(DEFAULT_DT),
            multitel_crust=sp6,
            multitel_ray=raysp6prem,
            perl_exe=exes["perl"],
            multitel_pl=exes["multitel3_pl"],
            multitel_bin=exes["multitel3_exe"],
            rayinfo_bin=exes["rayinformation"],
        )

        crust = parse_multitel_crust(sp6)
        ray_rows = parse_multitel_ray(raysp6prem)
        _ensure_ray_has_q(ray_rows, raysp6prem)
        tel_layers_raw = _build_tel_layers_to_cmb_with_core_halfspace(ray_rows)
        src_layers = _sp6_source_to_cps_src_layers(crust["source"], ray_rows)
        rec_layers = _sp6_source_to_cps_src_layers(crust["receiver"], ray_rows)

        cps_p_dir, cps_s_dir, tel_model, src_model, rec_model, _ = _run_cps_fixed_layers(
            work_root=work_root,
            depth_km=float(args.depth_km),
            gcarc_deg=float(args.gcarc_deg),
            npts=int(DEFAULT_NPTS),
            dt=float(DEFAULT_DT),
            tel_layers_raw=tel_layers_raw,
            src_layers=src_layers,
            rec_layers=rec_layers,
            hudson96=exes["hudson96"],
            hpulse96=exes["hpulse96"],
            f96tosac=exes["f96tosac"],
        )

        _copy_hudson_models_to_output(
            output_root=output_root,
            tel_model=tel_model,
            src_model=src_model,
            rec_model=rec_model,
        )

        d_records = load_records(m_direct_dir, source="multitel_direct", model="sp6")
        c_records = load_records(m_core_dir, source="multitel_core", model="sp6")
        p_records = load_records(cps_p_dir, source="cps_p", model="sp6")
        s_records = load_records(cps_s_dir, source="cps_s", model="sp6")

        d_map = _select_by_depth_gcarc(
            d_records,
            depth_km=float(args.depth_km),
            gcarc_deg=float(args.gcarc_deg),
            depth_tol=float(DEFAULT_DEPTH_TOL),
            gcarc_tol=float(DEFAULT_GCARC_TOL),
        )
        c_map = _select_by_depth_gcarc(
            c_records,
            depth_km=float(args.depth_km),
            gcarc_deg=float(args.gcarc_deg),
            depth_tol=float(DEFAULT_DEPTH_TOL),
            gcarc_tol=float(DEFAULT_GCARC_TOL),
        )
        p_map = _select_by_depth_gcarc(
            p_records,
            depth_km=float(args.depth_km),
            gcarc_deg=float(args.gcarc_deg),
            depth_tol=float(DEFAULT_DEPTH_TOL),
            gcarc_tol=float(DEFAULT_GCARC_TOL),
        )
        s_map = _select_by_depth_gcarc(
            s_records,
            depth_km=float(args.depth_km),
            gcarc_deg=float(args.gcarc_deg),
            depth_tol=float(DEFAULT_DEPTH_TOL),
            gcarc_tol=float(DEFAULT_GCARC_TOL),
        )

        combo_map: Dict[str, GFRecord] = {}
        for comp in COMPONENTS:
            dr = d_map.get(comp)
            cr = c_map.get(comp)
            if dr is None or cr is None:
                continue
            combo_map[comp] = _combine_direct_core(dr, cr)
        cps_map = _merge_cps_maps(p_map, s_map)

        _assert_has_9(d_map, "multitel_direct")
        _assert_has_9(combo_map, "multitel_direct_plus_core")
        _assert_has_9(cps_map, "cps_merged")

        _export_record_map(d_map, direct_out)
        _export_record_map(combo_map, combo_out)
        _export_record_map(cps_map, cps_out)

        fig_png = fig_out_dir / f"gf_compare_depth{args.depth_km:.2f}_gcarc{args.gcarc_deg:.2f}.png"
        _plot_compare(
            direct_map=d_map,
            combo_map=combo_map,
            cps_map=cps_map,
            depth_km=float(args.depth_km),
            gcarc_deg=float(args.gcarc_deg),
            out_png=fig_png,
            window_pre=float(DEFAULT_WINDOW_PRE),
            window_post=float(DEFAULT_WINDOW_POST),
        )

        print(f"done: outputs in {output_root}")
    finally:
        if work_root.exists():
            shutil.rmtree(work_root, ignore_errors=True)


def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Lightweight multitel3 vs CPS GF compare (fixed sp6/raysp6prem).",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--depth-km", type=float, required=True, help="Source depth (km).")
    parser.add_argument("--gcarc-deg", type=float, required=True, help="Epicentral distance (deg).")
    parser.add_argument("--output-dir", required=True, help="Output directory.")
    return parser.parse_args(argv)


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = parse_args(argv)
    _run_pipeline(args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
